### ISSUE TITLE
bug: header element is not found in cryptcheck

### ISSUE THREAD

**Issue by HagenMorano** [DanielRuf/website-checks#5]
Got the following error running `website-checks example.com`
```
(node:30514) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'style' of null
    at __puppeteer_evaluation_script__:1:40
    at ExecutionContext.evaluateHandle (/home/hmorano/.config/yarn/global/node_modules/puppeteer/lib/ExecutionContext.js:121:13)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async ExecutionContext.evaluate (/home/hmorano/.config/yarn/global/node_modules/puppeteer/lib/ExecutionContext.js:48:20)
    at async cryptcheck (/home/hmorano/.config/yarn/global/node_modules/website-checks/index.js:91:3)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/home/hmorano/.config/yarn/global/node_modules/puppeteer/lib/helper.js:108:27)
    at ExecutionContext.evaluate (/home/hmorano/.config/yarn/global/node_modules/puppeteer/lib/ExecutionContext.js:48:31)
    at ExecutionContext.<anonymous> (/home/hmorano/.config/yarn/global/node_modules/puppeteer/lib/helper.js:109:23)
    at DOMWorld.evaluate (/home/hmorano/.config/yarn/global/node_modules/puppeteer/lib/DOMWorld.js:105:20)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
  -- ASYNC --
    at Frame.<anonymous> (/home/hmorano/.config/yarn/global/node_modules/puppeteer/lib/helper.js:108:27)
    at Page.evaluate (/home/hmorano/.config/yarn/global/node_modules/puppeteer/lib/Page.js:809:43)
    at Page.<anonymous> (/home/hmorano/.config/yarn/global/node_modules/puppeteer/lib/helper.js:109:23)
    at cryptcheck (/home/hmorano/.config/yarn/global/node_modules/website-checks/index.js:91:14)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
(node:30514) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:30514) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

_edit_ Worked on second try

**Comment by DanielRuf** [comment]
Ok, seems this is a race condition with `cryptcheck`.

`at cryptcheck (/home/hmorano/.config/yarn/global/node_modules/website-checks/index.js:91:14)`

I will add a try-catch and check the code.

**Comment by DanielRuf** [comment]
https://github.com/DanielRuf/website-checks/blob/master/index.js#L91

Seems the header took a bit longer to load. I will add `waitForSelector` as an additional safeguard.

**Comment by DanielRuf** [comment]
Interestingly none of the builds showed this error.

https://travis-ci.com/DanielRuf/website-checks

https://travis-ci.com/DanielRuf/website-checks/builds

**Comment by DanielRuf** [comment]
Side note: probably related to the outage of their server this week and the website was not correctly loading. `header` exists in the raw DOM.

**Comment by DanielRuf** [comment]
@HagenMorano can you test again?

**Comment by HagenMorano** [comment]
Error did not occur again. Closing.
